repos:
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black
      language_version: python3.12
      args: [
            --exclude,
            '(lgw/settings.py)',
            --skip-string-normalization
      ]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-ast
    - id: end-of-file-fixer
    - id: double-quote-string-fixer
    - id: trailing-whitespace
    - id: no-commit-to-branch
